import re
from typing import Tuple, Dict, Any, Optional
from ai.llm import get_llm_instance
from ai.prompt import sql_gen_prompt
from ai.schema_reader import get_database_schema_prompt_text, get_table_metadata
from ai.sql_validator import validate_sql_query
from rag.retriever import get_schema_retriever
from utils.logger import logger

def generate_sql_query(
    question: str,
    table_name: str,
    provider: str = "gemini",
    api_key: Optional[str] = None,
    model_name: Optional[str] = None
) -> Tuple[str, str]:
    """
    Generates a SQL query from natural language question.
    Uses LLM (Gemini / OpenAI) with LangChain + RAG context if key is available,
    otherwise uses an intelligent rule-based heuristic SQL generator.

    Returns:
        (generated_sql, metadata_msg)
    """
    logger.info(f"Generating SQL query for question: '{question}' on table '{table_name}'")

    # 1. Fetch schema context
    schema_text = get_database_schema_prompt_text(table_name)
    
    # 2. Fetch RAG context
    try:
        retriever = get_schema_retriever(table_name)
        rag_context = retriever.get_relevant_context(question)
    except Exception as e:
        logger.warning(f"RAG retrieval skipped: {e}")
        rag_context = ""

    # 3. Try LLM Generation if LLM instance available
    llm = get_llm_instance(provider=provider, api_key=api_key, model_name=model_name)
    
    if llm is not None:
        try:
            formatted_prompt = sql_gen_prompt.format(
                schema_context=schema_text,
                rag_context=rag_context,
                question=question
            )
            
            response = llm.invoke(formatted_prompt)
            raw_sql = response.content if hasattr(response, 'content') else str(response)
            
            # Clean SQL output (strip markdown backticks if any)
            clean_sql = re.sub(r'```sql\s*', '', raw_sql, flags=re.IGNORECASE)
            clean_sql = re.sub(r'```\s*', '', clean_sql)
            clean_sql = clean_sql.strip().rstrip(';')

            is_valid, msg = validate_sql_query(clean_sql)
            if is_valid:
                return clean_sql, f"Generated by {provider.upper()} LLM"
            else:
                logger.warning(f"LLM produced invalid SQL: {msg}. Falling back to Rule Engine.")
        except Exception as e:
            logger.error(f"LLM generation failed: {e}. Falling back to Rule Engine.")

    # 4. Fallback Rule-Based SQL Generator
    fallback_sql = _generate_rule_based_sql(question, table_name)
    return fallback_sql, "Generated by Rule-Based Engine (Offline Mode)"

def _generate_rule_based_sql(question: str, table_name: str) -> str:
    """
    Intelligent offline rule-based SQL generator.
    Parses intent (top N, singular highest/lowest, group by, sum, avg, count, trend)
    and uses scoring-based semantic token matching to select the exact target schema columns.
    """
    meta = get_table_metadata(table_name)
    columns = meta.get("columns", [])
    dtypes = meta.get("dtypes", {})
    
    q_lower = question.lower()

    # Identify numeric, text, and date columns
    numeric_cols = [col for col, dt in dtypes.items() if any(x in dt.lower() for x in ['int', 'float', 'double', 'real', 'num', 'bigint', 'decimal'])]
    text_cols = [col for col in columns if col not in numeric_cols]
    date_cols = [col for col in columns if any(x in col.lower() for x in ['date', 'time', 'year', 'month', 'day'])]

    # 1. Extract explicit limit if specified (e.g., top 5, first 3, limit 10)
    limit_match = re.search(r'\btop\s+(\d+)\b|\bfirst\s+(\d+)\b|\blimit\s+(\d+)\b', q_lower)
    if limit_match:
        limit_val = int(next(g for g in limit_match.groups() if g is not None))
    else:
        # Check if asking singular question ("which product...", "what store...", "who...", "highest...", "maximum...")
        is_singular = any(w in q_lower for w in ['which', 'what', 'who', 'single', 'best', 'top store', 'top product']) or \
                      any(w in q_lower for w in ['highest', 'best', 'most', 'maximum', 'max', 'lowest', 'worst', 'least', 'minimum', 'min'])
        limit_val = 1 if is_singular else 5

    # 2. Advanced Scoring-Based Column Matcher
    def score_column(col: str, is_numeric: bool) -> float:
        col_lower = col.lower()
        score = 0.0
        
        # Keyword-specific scoring for numeric metric columns
        if is_numeric:
            if 'sales' in q_lower:
                if 'sales' in col_lower: score += 10.0
                if col_lower in ['total_sales', 'sales']: score += 5.0
            if 'profit' in q_lower or 'margin' in q_lower:
                if 'profit' in col_lower or 'margin' in col_lower: score += 10.0
            if any(k in q_lower for k in ['quantity', 'qty', 'volume', 'units']):
                if any(k in col_lower for k in ['quantity', 'qty', 'units']): score += 10.0
            if any(k in q_lower for k in ['price', 'cost', 'expense', 'rate']):
                if any(k in col_lower for k in ['price', 'cost', 'expense', 'unit_price']): score += 10.0
            if 'discount' in q_lower:
                if 'discount' in col_lower: score += 10.0
        else:
            # Categorical column keyword scoring
            if 'product' in q_lower and 'product' in col_lower: score += 10.0
            if 'store' in q_lower and 'store' in col_lower: score += 10.0
            if 'region' in q_lower and 'region' in col_lower: score += 10.0
            if any(k in q_lower for k in ['salesperson', 'rep', 'manager', 'agent', 'employee']) and any(k in col_lower for k in ['salesperson', 'manager', 'employee', 'rep']): score += 10.0
            if 'customer' in q_lower and 'customer' in col_lower: score += 10.0
            if 'category' in q_lower and 'category' in col_lower: score += 10.0
            if 'city' in q_lower and 'city' in col_lower: score += 10.0

        # Quarter matching (q1, q2, q3, q4)
        for q_quarter in ['q1', 'q2', 'q3', 'q4']:
            if q_quarter in q_lower and q_quarter in col_lower:
                score += 15.0

        # Token overlap matching
        parts = col_lower.split('_')
        for p in parts:
            if len(p) > 2 and p in q_lower:
                score += 3.0
                
        if col_lower in q_lower:
            score += 8.0
            
        return score

    # Find best matching text column
    best_text_col = None
    best_text_score = -1.0
    for col in text_cols:
        s = score_column(col, is_numeric=False)
        if s > best_text_score:
            best_text_score = s
            best_text_col = col

    # Find best matching numeric column
    best_num_col = None
    best_num_score = -1.0
    for col in numeric_cols:
        s = score_column(col, is_numeric=True)
        if s > best_num_score:
            best_num_score = s
            best_num_col = col

    matched_text_col = best_text_col if (best_text_col and best_text_score > 0) else (text_cols[0] if text_cols else columns[0])
    matched_num_col = best_num_col if (best_num_col and best_num_score > 0) else (numeric_cols[0] if numeric_cols else columns[-1])

    # Define alias name cleanly
    alias_num = matched_num_col if matched_num_col.startswith('total_') else f"total_{matched_num_col}"

    # Pattern 1: Monthly / Date Trend
    if date_cols and any(w in q_lower for w in ['trend', 'month', 'monthly', 'over time', 'daily', 'date', 'year']):
        date_col = date_cols[0]
        return f"SELECT {date_col}, SUM({matched_num_col}) AS {alias_num} FROM {table_name} GROUP BY {date_col} ORDER BY {date_col} LIMIT 50"

    # Pattern 2: Top / Highest / Best / Maximum / Which / What
    if any(w in q_lower for w in ['top', 'highest', 'best', 'most', 'maximum', 'max', 'which', 'what', 'who']):
        if not any(w in q_lower for w in ['lowest', 'worst', 'least', 'minimum', 'min']):
            return f"SELECT {matched_text_col}, SUM({matched_num_col}) AS {alias_num} FROM {table_name} GROUP BY {matched_text_col} ORDER BY {alias_num} DESC LIMIT {limit_val}"

    # Pattern 3: Lowest / Worst / Minimum
    if any(w in q_lower for w in ['lowest', 'worst', 'least', 'minimum', 'min']):
        return f"SELECT {matched_text_col}, SUM({matched_num_col}) AS {alias_num} FROM {table_name} GROUP BY {matched_text_col} ORDER BY {alias_num} ASC LIMIT {limit_val}"

    # Pattern 4: Average / Mean by Category
    if any(w in q_lower for w in ['average', 'avg', 'mean']):
        alias_avg = matched_num_col if matched_num_col.startswith('avg_') else f"avg_{matched_num_col}"
        return f"SELECT {matched_text_col}, AVG({matched_num_col}) AS {alias_avg} FROM {table_name} GROUP BY {matched_text_col} ORDER BY {alias_avg} DESC LIMIT {limit_val}"

    # Pattern 5: Total / Sum / Aggregation by Category
    if any(w in q_lower for w in ['total', 'sum', 'overall', 'by', 'breakdown', 'per']):
        return f"SELECT {matched_text_col}, SUM({matched_num_col}) AS {alias_num} FROM {table_name} GROUP BY {matched_text_col} ORDER BY {alias_num} DESC LIMIT {limit_val}"

    # Pattern 6: Count of items / records
    if any(w in q_lower for w in ['count', 'how many', 'number of']):
        if text_cols:
            return f"SELECT {matched_text_col}, COUNT(*) AS count FROM {table_name} GROUP BY {matched_text_col} ORDER BY count DESC LIMIT {limit_val}"
        return f"SELECT COUNT(*) AS total_records FROM {table_name}"

    # Default fallback
    select_cols = ", ".join(columns[:6]) if columns else "*"
    return f"SELECT {select_cols} FROM {table_name} LIMIT {limit_val}"



